#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.0
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Phoneword_Droid.Resource", IsApplication=true)]

namespace Phoneword_Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int CallButton = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int CallHistoryButton = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int PhoneNumberText = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int TranslateButton = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int textView1 = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int AppName = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int CallHistory = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int CallText = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int PhoneText = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int Text = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int TranslateText = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
